services:
  - type: web
    name: mastodon-web
    env: docker
    repo: https://github.com/mastodon/mastodon
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DB_HOST
        fromService:
          type: postgres
          name: mastodon-db
          property: host
      - key: REDIS_HOST
        fromService:
          type: redis
          name: mastodon-redis
          property: host
      - key: WEB_DOMAIN
        value: yourdomain.onrender.com
      - key: LOCAL_DOMAIN
        value: yourdomain.onrender.com

  - type: worker
    name: mastodon-sidekiq
    env: docker
    repo: https://github.com/mastodon/mastodon
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DB_HOST
        fromService:
          type: postgres
          name: mastodon-db
          property: host
      - key: REDIS_HOST
        fromService:
          type: redis
          name: mastodon-redis
          property: host

  - type: web
    name: mastodon-streaming
    env: docker
    repo: https://github.com/mastodon/mastodon
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production

  - type: postgres
    name: mastodon-db
    plan: free

  - type: redis
    name: mastodon-redis
    plan: free
    ipAllowList: 
      - source: 0.0.0.0/0
        description: allow all
